[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo_mysql", "php82Extensions.mbstring", "php82Extensions.bcmath", "php82Extensions.gd", "php82Extensions.zip", "composer"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader --no-interaction"
]

[start]
cmd = "php artisan migrate --force && php -S 0.0.0.0:$PORT -t public"